spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jejudata
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        use_sql_comments: true
#  thymeleaf:
#    prefix: classpath:src/main/resources/
#    check-template-location: true
#    suffix: .html
#    mode: HTML
#    cache: false
#    order: 0

logging.level:
  org.hibernate.SQL: debug
  #  org.hibernate.type: trace